name: Deploy(Release version)

on:
  release:
    types: [published]

jobs:
  deploy-release:
    runs-on: ubuntu-latest
    steps:
      - name: Setup secret_key
        run: |
          echo -e "${{ secrets.SSH_PRIVATE_KEY }}" > secret_key
          chmod 600 secret_key
      - name: Deploy
        run: |
          echo ${GITHUB_REF}
          echo ${GITHUB_REF##*/}
          ssh -oStrictHostKeyChecking=no root@api.kakomimasu.com -i secret_key <<EOC
          cd ~/server-release
          git fetch
          systemctl stop kakomimasu-release
          git checkout -B ${GITHUB_REF##*/} ${GITHUB_REF}
          systemctl start kakomimasu-release
          EOC
