name: CI

on: [push,pull_request]

jobs:
  check:
    name: deno format & lint check
    uses: kakomimasu/kakomimasu.github.io/.github/workflows/dfl-check.yml@main
  test:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Firebase Emulator
        working-directory: ./firebase-emulator
        run: ./setup.sh
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.26.1
      - name: Run cache & check
        run: |
          deno task cache
      - name: Run test
        env:
          FIREBASE_USERNAME: test@example.com
          FIREBASE_PASSWORD: server-admin
          FIREBASE_TEST: true
        run: |
          firebase emulators:exec --import ./data/ "deno task test-ci"