name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    name: format & lint check
    uses: kakomimasu/kakomimasu.github.io/.github/workflows/dfl-check.yml@main
  test:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Firebase Emulator
        shell: bash -xe {0}
        run: |
          curl -sL https://firebase.tools | upgrade=true bash
          firebase setup:emulators:database
          firebase setup:emulators:firestore
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.33.3
      - name: Run cache & check
        run: |
          deno task cache
      - name: Create Firebase service account
        run: |
          echo -n "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}"" > ./firebase-key.json
      - name: Run test
        env:
          GOOGLE_APPLICATION_CREDENTIALS: "firebase-key.json"
          FIREBASE_DATABASE_EMULATOR_HOST: ${{ secrets.FIREBASE_DATABASE_EMULATOR_HOST }}
          FIREBASE_AUTH_EMULATOR_HOST: ${{ secrets.FIREBASE_AUTH_EMULATOR_HOST}}
        run: |
          deno task ci:test
      - name: Create coverage
        run: |
          deno task coverage
      - name: Codecov
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage/coverage.lcov
