name: Deno Test

on: [push,pull_request]

jobs:
  check:
    uses: kakomimasu/kakomimasu.github.io/.github/workflows/dfl-check.yml@main
    with:
      config_file: deno.json
  test:
    needs: check
    runs-on: ubuntu-latest
    services:
      firebase-emulator:
        image: ghcr.io/kakomimasu/firebase-emulator:latest
        ports:
          - 8080:8080
          - 9000:9000
          - 9099:9099
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.20.3
      - name: Run cache & check
        run: |
          deno task cache
      - name: Run test
        if: ${{ runner.os != 'Windows' }}
        env:
          FIREBASE_USERNAME: test@example.com
          FIREBASE_PASSWORD: server-admin
          FIREBASE_TEST: true
        run: |
          deno task start > /dev/null &
          deno task test
