name: Deno Test

on: [push,pull_request]

jobs:
  check:
    uses: kakomimasu/kakomimasu.github.io/.github/workflows/dfl-check.yml@main
    with:
      config_file: deno.json

  test:
    needs: check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest,macos-latest,windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Run cache & check
        run: |
          deno cache ./server.ts
      - name: Run test
        if: ${{ runner.os == 'Windows' }}
        env:
          FIREBASE_USERNAME: ${{secrets.FIREBASE_USERNAME}}
          FIREBASE_PASSWORD: ${{secrets.FIREBASE_PASSWORD}}
          FIREBASE_TEST: true
        run: |
          deno run -A --location http://localhost server.ts > $null &
          deno test -A --location http://localhost
      - name: Run test
        if: ${{ runner.os != 'Windows' }}
        env:
          FIREBASE_USERNAME: ${{secrets.FIREBASE_USERNAME}}
          FIREBASE_PASSWORD: ${{secrets.FIREBASE_PASSWORD}}
          FIREBASE_TEST: true
        run: |
          deno run -A --location http://localhost server.ts > /dev/null &
          deno test -A --location http://localhost
