name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    name: format & lint check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.0.2
      - name: Run fmt
        run: deno fmt --check
      - name: Run lint
        run: deno lint
  test:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.0.2
      - name: Run test
        run: |
          deno task test
      - name: Create coverage
        run: |
          deno task coverage
      - name: Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage/coverage.lcov
