name: udd check

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  udd-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Git config
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Install udd
        run: |
          deno install -A -f -n udd https://deno.land/x/udd/main.ts
      - name: Check Update
        run: |
          udd deps.ts
      - name: Git diff
        id: diff
        run: |
          git add deps.ts
          if git diff --exit-code deps.ts ; then
            echo "::set-output name=changes_exist::true"
          else
            echo "::set-output name=changes_exist::false"
          fi
      - name: Git checkout
        if: steps.diff.outputs.changes_exist == 'true'
        run: | 
          git checkout -b actions/udd
      - name: Git commit
        if: steps.diff.outputs.changes_exist == 'true'
        run: |
          git commit -m "Update dependency"
          # git push --set-upstream origin actions/udd
      - name: Generate token
        if: steps.diff.outputs.changes_exist == 'true'
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
      - name: Create Pull Request
        if: steps.diff.outputs.changes_exist == 'true'
        run: gh pr create --title "Update Deno Dependency" --body "" --head default
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}